### PR TITLE
chore: search bar style nits

### PR DESCRIPTION
**Pull request by rudouglas**

### CODE REVIEW

**Comment by LizBaker** [comment]
this is looking good! I did notice one issue: this wraps in a weird way with a smaller screen width (this is around 1400px which is the size I usually have it on my 13in laptop)
Screen Shot 2021-07-12 at 10 37 09 AM

**Comment by aswanson-nr** [comment]
Overall this looks great! I just noticed two small things:
1. The search bar pushes content out of the surrounding container at certain break points.
Screen Shot 2021-07-12 at 2 55 51 PM

2. Is it possible to increase the size of the magnifying glass icon?

**Comment by rudouglas** [comment]
Thanks for the feedback @LizBaker @aswanson-nr, i've added some media breaks to deal width the sizing issues, and also increased the size of the `Search Icon Button` to make it more visible 🥳

**Review by aswanson-nr — COMMENTED** [review]
LGTM

**Review by aswanson-nr — APPROVED** [review]

**Pull request merged**
