### PR TITLE
Edit pass Quickly tag resources

### PR DESCRIPTION
**Pull request by mmfred**
Some edits to the file.

## Description
I hadn't done a thorough edit pass previously.

## Reviewer Notes
I have some notes to add for the writer to review. I'll add them in the PR.

### CODE REVIEW

**Review by mmfred — COMMENTED** [review]
@theletterf - I edited this file and have a few questions re the content. Please also take a look at the recommended changes in this PR.

Questions:
- For the intro, I was looking for a use case or two about what to do with tagged entities. Also, there's the mention of automating the process. Are you saying the process we've provided here is automated? 
- What's the purpose of the New Relic CLI profile? Is it necessary just to run the CLI at all?
- Similarly, why set the region?
- There's a note that says,  "Adding tags is an asynchronous operation: it could take a little while for the tags to get created." What's a little while, in this case? How are the tags actually created?

**Comment by jpvajda** [comment]
@mmfred is this still a working PR we should keep open?

**Comment by jerelmiller** [comment]
This seems stale. I'm going to go ahead and close this for now. Feel free to open this back up if you'd like to see this work added in.

**Comment by alexronquillo** [comment]
@jpvajda @jerelmiller This PR has two parts:

1. Edits that @mmfred made to the document
2. Questions about missing context in some areas

The questions in (2) were directed at Fabrizio, who used to be on the docs team. Because he's not working on this anymore, I'll take it over and try to answer some of those questions and supply the context in the document. I'll create a separate issue to track those changes. For now, let's merge @mmfred's edits.

**Comment by jerelmiller** [comment]
@alexronquillo fantastic! It looks like there are some merge conflicts on one of the guides. If you could help resolve that, I'd be happy to merge these edits in!

**Review by alexronquillo — APPROVED** [review]
Thanks, @jerelmiller! This is ready to go 🚀

**Review by jerelmiller — APPROVED** [review]

**Pull request merged**
