### PR TITLE
Draft - feat: added quickstarts page

### PR DESCRIPTION
**Pull request by kidk**
## Description

Added description for customers on how to use quickstarts.

## Reviewer Notes

Please let me know if I need to add anything else, or if more information is needed.

@jaesius

### CODE REVIEW

**Comment by jpvajda** [comment]
It's not clear to me what this PR is intending to do. @kidk can you give us some insights into why you are submitting this PR?

**Comment by kidk** [comment]
Thanks @jpvajda I'm waiting on @jaesius to take a look, and see if it fits with the dashboard story.

**Comment by jpvajda** [comment]
@kidk Ok, Where exactly is this intending this content to be placed? currently you just have this file floating"outside the primary navigation of the site, so that's why I was asking. If you are looking to create navigation for this, or add it to an existing nav section you can refer to our [contributing guide](https://github.com/newrelic/developer-website/blob/develop/CONTRIBUTING.md#guidelines-for-contributing) on getting that all configured. 

Also, if you intend to work from Draft PRS, you can leave them as draft in github, vs just labeling them as draft. 

https://github.blog/2019-02-14-introducing-draft-pull-requests/

Thanks!

**Comment by kidk** [comment]
Thanks @jpvajda I'll close this one for now and create one in draft once I've adapt it based in your message.

**Pull request closed without merging**
