### PR TITLE
chore: replace image to have correct breadcrumb pathway from i/o

### PR DESCRIPTION
**Pull request by brammerl**
## Description

This PR replaces an image to use the correct breadcrumb pathway from i/o rather than app

## Reviewer Notes

If there are links or steps needed to test this work, add them here.

## Related Issue(s) / Ticket(s)

* [issue](https://newrelic.atlassian.net/jira/software/c/projects/DEVEX/boards/1581?modal=detail&selectedIssue=DEVEX-2061)

## Screenshot(s)

Updated image: 
New image

Clear resolution on local build: 
Screen Shot 2021-11-29 at 2 12 13 PM

## Use Conventional Commits

Please help the maintainers by leveraging the following [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/)
standards in your pull request title and commit messages.

## Use `chore`

* for minor changes / additions / corrections to content.
* for minor changes / additions / corrections to images.
* for minor non-functional changes / additions to github actions, github templates, package or config updates, etc

```bash
git commit -m "chore: adjusting config and content"
```

## Use `fix`

* for minor functional corrections to code.

```bash
git commit -m "fix: typo and prop error in the code of conduct"
```

## Use `feat`

* for major functional changes or additions to code.

```bash
git commit -m "feat(media): creating a video landing page"
```

### CODE REVIEW

**Comment by jerelmiller** [comment]
@brammerl it looks like the image is quite a bit smaller than the image it replaced. I just checked it on the [PR build](https://developerwebsitedevelop-luciachangeimage.gtsb.io/build-apps/publish-deploy/subscribe/) and it does look quite a bit blurrier. Could we get a bit higher res screenshot?

**Review by jerelmiller — CHANGES_REQUESTED** [review]
Requesting a higher-res screenshot so that the image is not as blurry.

**Comment by jpvajda** [comment]
@brammerl I'm not sure on our standard here, but exposing an actual account ID in the public may not be that great, I'm not sure which account ID this is for, but do you want to just cover that actual ID in this screen shot with a blur effect?

**Review by jpvajda — CHANGES_REQUESTED** [review]
I had a suggestion...

**Comment by brammerl** [comment]
> @brammerl I'm not sure on our standard here, but exposing an actual account ID in the public may not be that great, I'm not sure which account ID this is for, but do you want to just cover that actual ID in this screen shot with a blur effect?

Hi! That image is the original image with a different breadcrumb pathway edited over it. It's currently exposed on the developer website on that page in 2 places. subscribe and unsubscribe from your app. I'm happy to blur those out!

**Comment by tyreer** [comment]
You could also just "Edit as HTML" in the console and make the account `1234567` in both spots if you want to avoid the blur

**Comment by brammerl** [comment]
> You could also just "Edit as HTML" in the console and make the account `1234567` in both spots if you want to avoid the blur image

So, the images were edited  by inserting a screenshot of the breadcrumb and overlaying that image ontop of the original one. I'm not able to manually change the id because of that. I'm leaning more towards just blurring them out.

**Comment by tyreer** [comment]
Ah I see, I think blurring works then

**Comment by brammerl** [comment]
@jpvajda @jerelmiller I addressed all of the comments above. Let me know what you think!

**Review by jpvajda — APPROVED** [review]

**Comment by jpvajda** [comment]
@brammerl thanks! that took care of my feedback. 🎨

**Review by jerelmiller — APPROVED** [review]
Thanks! Image resolution is much better. Appreciate it!

**Pull request merged**
