### PR TITLE
chore:add instruction for undeploying an app

### PR DESCRIPTION
**Pull request by bytrangle**
## Description

This pull request adds a new section for showing users how to undeploying an app on New Relic.

It contains three steps:
- Get a list of subscribed deployed Nerdpacks for a New Relic account.
- Unsubscribe a particular Nerdpack ID from the account.
- Undeploy that Nerdpack ID.

### CODE REVIEW

**Comment by jerelmiller** [comment]
@bytrangle Thanks so much for submitting this update! This is super useful.

@mmfred would you or a member of the docs team be willing to review the updates here? Thanks!

**Review by mmfred — COMMENTED** [review]
This looks good from a writing standpoint. I separated out some commands.

**Review by jerelmiller — APPROVED** [review]
This looks great! Thanks a bunch for your contribution!

**Comment by bytrangle** [comment]
> This looks great! Thanks a bunch for your contribution!

Thank you. This is the first contribution in my coding career so that means a lot.

**Pull request merged**
