### PR TITLE
chore: Styling nits for I/O

### PR DESCRIPTION
**Pull request by rudouglas**
## Acceptance Criteria
* [x] Header should not be bold (set it to `600`)
* [x] Super tile should have a font size of `14` and the line height should be `20`
* [x] Use the "small" button style for super tile CTA
* [x] Set placeholder text for search to `14` (font size and line height)
* [x] Update the layout icon to be `24`px
* [x] Reduce the unnecessary height for the tiles

### CODE REVIEW

**Review by josephgregoryii — DISMISSED** [review]
Looks good! Matches the ticket designs to me

**Comment by jpvajda** [comment]
could we merge this in now?

**Review by jpvajda — COMMENTED** [review]
I noticed a lot of eslint warnings in this PR. is that expected? But the design changes LGTM.

**Comment by josephgregoryii** [comment]
@jpvajda The linting warnings is from the integration of TypeScript + TypeScript linter/parser. Theyre only warnings and are there to _suggest_ switching the file over to typescript :)

**Review by zstix — APPROVED** [review]

**Pull request merged**
