### PR TITLE
chore: fixed use of old tip component

### PR DESCRIPTION
**Pull request by jpvajda**
## Description
- fixes the use of the old tip component in a couple guides. 
- fixes the "double" table on the API index page.

### CODE REVIEW

**Review by zstix — APPROVED** [review]

**Review by zstix — CHANGES_REQUESTED** [review]
Looks like we're missing this in a few places (i.e. [error-alerts.mdx](https://github.com/newrelic/developer-website/blame/develop/src/markdown-pages/automate-workflows/diagnose-problems/error-alerts.mdx#L38))

**Comment by jpvajda** [comment]
@zstix good catch! I fixed that in the recent commit.

**Comment by jpvajda** [comment]
@zstix just need a thumb on this when you have a moment

**Review by zstix — APPROVED** [review]
💯

**Pull request merged**
