### PR TITLE
fix(sonic): fix broken terraform doc external redirects

### PR DESCRIPTION
**Pull request by bradleycamacho**
Fixes external redirects introduced in #2206

### CODE REVIEW

**Review by roadlittledawn — COMMENTED** [review]
Why redirecting to docs URLs with no trailing slash?

**Comment by bradleycamacho** [comment]
> Why redirecting to docs URLs with no trailing slash?

I just noticed that's what we do for the rest of the redirects so I just followed the same pattern!

**Review by jeff-colucci — APPROVED** [review]
Looks good to me

**Review by akristen — APPROVED** [review]
Lin ks work!

**Pull request merged**
