### PR TITLE
Charts guide

### PR DESCRIPTION
**Pull request by alexronquillo**
## Description

Reorganized chart component content and added an overview guide.

## Reviewer Notes

Please sanity check that I didn't break links by updating the hierarchy.

## Related Issue(s) / Ticket(s)

https://github.com/newrelic/developer-website/issues/975

### CODE REVIEW

**Comment by jpvajda** [comment]
@alexronquillo Thanks for submitting this PR, I'll pull it down to tomorrow and give it a glance, unfortunately the Amplify AWS preview isn't work for this change. :(

**Comment by jerelmiller** [comment]
Not sure why Amplify isn't posting back the result, but the build was successful. Here is a link to the preview: https://pr-1030.dlyi50rq9kt6c.amplifyapp.com/

FWIW, assuming the build succeeds, all PR previews will be in this structure. Replace the number in that link above with the PR number and you'll be able to access any open PR preview.

**Comment by alexronquillo** [comment]
@jerelmiller works for me! That's an awesome feature!

**Comment by jpvajda** [comment]
@jerelmiller ah good to know! it be cool if those preview links appeared in the github actions section of a PR, like netlify does it. :)

**Comment by jerelmiller** [comment]
> ah good to know! it be cool if those preview links appeared in the github actions section of a PR

It sorta does that, but seems like Amplify doesn't do a great job sometimes of reporting back on the status. Not sure why. We'll have to see if Amplify has any other means of displaying the preview status or not.

**Review by jpvajda — APPROVED** [review]
LGTM! This is a great guide!

**Comment by jaesius** [comment]
Great guide!

**Pull request merged**
