### PR TITLE
chore: bump theme

### PR DESCRIPTION
**Pull request by jpvajda**
This PR bumps the theme which removes UTM params from the sign up button clicks, which `should` resolve some analytics problems.

### CODE REVIEW

**Comment by jpvajda** [comment]
Relates to https://github.com/newrelic/docs-website/issues/1816

**Comment by jerelmiller** [comment]
Can you update and push `yarn.lock` as well to ensure that the build properly installs the new version?

**Comment by jerelmiller** [comment]
Hello by the way! 👋

**Comment by jpvajda** [comment]
@jerelmiller 👋  hello! I pushed that change as well.

**Comment by jerelmiller** [comment]
Interesting, looks like there might be a bug or something in the new version of the theme. Or something here is incompatible. The build failed.

**Comment by jpvajda** [comment]
I'm looking into this error:

```
SiteSiteMetadata.utmSource provided incorrect OutputType: 'Object({
resolve: [function wrappedTracingResolver], extensions: Object({
createdFrom: "createResolvers" }) })'



  Error: SiteSiteMetadata.utmSource provided incorrect OutputType: 
'Object({ resolve: [function wrappedTr  acingResolver], extensions: 
Object({ createdFrom: "createResolvers" }) })'
```

**Comment by jpvajda** [comment]
closing for this PR https://github.com/newrelic/developer-website/pull/1256

**Pull request closed without merging**
