### PR TITLE
Rename packId to quickstartId in install url

### PR DESCRIPTION
**Pull request by LizBaker**
This PR works in tandem with the refactor PR of the nerdlet. Changing the packId provided in the nr1 url to quickstartId in the dev site and consuming quickstartId in the nerdlet

### CODE REVIEW

**Review by nr-kkenney — APPROVED** [review]
Small question, could we define both a staging & production environment / url?

**Comment by LizBaker** [comment]
@nr-kkenney the base url is going to be production once we get to a good point to come back and change it, and then you might use the base local one for development, but i don't think we need staging, does that make sense? or do you think they should be named differently?

**Comment by nr-kkenney** [comment]
that makes sense. i was just curious why we would swap this later, when we could define all three and just swap between them -- maybe using something like an environment variable.

**Comment by LizBaker** [comment]
@nr-kkenney totally down to do that when we go through and fix the todos!

**Pull request merged**
