### PR TITLE
fix: update to theme version that handles blocked cookies

### PR DESCRIPTION
**Pull request by aswanson-nr**
# Summary
Handle case when cookies are blocked.

Closes https://github.com/newrelic/docs-website/issues/2293

### CODE REVIEW

**Comment by roadlittledawn** [comment]
so far seems to be working okay. but i did see that embed pages seem to use dark mode when they should default to light mode. example: http://localhost:8000/automate-workflows/get-started-terraform/embed

**Comment by roadlittledawn** [comment]
Search works for me. And I don't think developer has any Collapser components

**Comment by aswanson-nr** [comment]
> so far seems to be working okay. but i did see that embed pages seem to use dark mode when they should default to light mode. example: http://localhost:8000/automate-workflows/get-started-terraform/embed
> 
> 

Here's the issue I put together for that problem https://github.com/newrelic/developer-website/issues/1335.

**Review by LizBaker — APPROVED** [review]
i'm good with moving forward despite the embed issue since we have it documented and someone having cookies entirely blocked is less likely

**Pull request merged**
