### PR TITLE
Updated Nerd Days page

### PR DESCRIPTION
**Pull request by danielgolden**
## This is a work in progress (tldr: 🤰  + ⏳ = 💻  🚧 )
This PR adds the markup and styles for the updated Nerd Days landing page design. This is a work in progress (that I'm submitting as a draft so that in case my wife gives birth this weekend, the team still has a way to carry the ball forward while I'm gone) so there are a lot of things to notes:
- From a development perspective, this page is ready to be pushed live to the dev site (pending a review, of course) _as a single landing page for nerd days_ (more on what I mean by that below).
- This isn't yet a template, just a landing page for nerd days. The "templatization" of this page is the plan, but for now to get something workable and accessible to the rest of the team this is just a single landing page while I work on it.
- There are no new components included in this PR. While several of the elements in this design should be made into components, for now they're all just markup and styles. Again, this along with the previous point are among the next tasks on my plate for this project.
- Dark mode hasn't been implemented yet
- There's a weird bug where the icons for the first two tracks disappear when the sidebar disappears (below 760px viewport width)

### Next steps
1. Create the components out of the appropriate elements on the page (and update the components guide)
2. Build out dark mode
3. Turn the page into a template (could use direction from the dev experience team when the time comes)

## Reviewer Notes
The page lives at `/nerd-days`

## Related Issue(s) / Ticket(s)
Very closely related to #694, but this PR doesn't yet contain the components and other changes that will allow this design to be implemented as a template.

### CODE REVIEW

**Comment by veextee** [comment]
[nerddayslandingpage-VTedits.pdf](https://github.com/newrelic/developer-website/files/5190120/nerddayslandingpage-VTedits.pdf)

For visibility, Nerd Days landing page copy attached. Open file to see post-it notes for each section and respective copy.

**Comment by jerelmiller** [comment]
Closing this PR in favor of #721 which is a copy of this PR, but in a branch inside the main repo.

**Comment by danielgolden** [comment]
You are a hero, @jerelmiller. Thanks for taking this across the finish line, man.

**Comment by jerelmiller** [comment]
You got it @danielgolden!

**Pull request closed without merging**
