### PR TITLE
chore: removing duplicate text from index.js

### PR DESCRIPTION
**Pull request by stumblefiend**
## Description

Remove the repeated text "software tools"

## Reviewer Notes

If there are links or steps needed to test this work, add them here.

## Related Issue(s) / Ticket(s)

If there are any related [GitHub Issues](https://github.com/newrelic/developer-website/issues) or JIRA tickets, add links to them here.
* [issue]()

## Screenshot(s)

If relevant, add screenshots here.

## Use Conventional Commits

Please help the maintainers by leveraging the following [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/)
standards in your pull request title and commit messages.

## Use `chore`

* for minor changes / additions / corrections to content.
* for minor changes / additions / corrections to images.
* for minor non-functional changes / additions to github actions, github templates, package or config updates, etc

```bash
git commit -m "chore: adjusting config and content"
```

## Use `fix`

* for minor functional corrections to code.

```bash
git commit -m "fix: typo and prop error in the code of conduct"
```

## Use `feat`

* for major functional changes or additions to code.

```bash
git commit -m "feat(media): creating a video landing page"
```

### CODE REVIEW

**Review by jerelmiller — COMMENTED** [review]
@stumblefiend this is a really good find! Thanks so much for fixing this!

It looks like the change resulted in an ESLint issue. Would you mind fixing that? I'd be happy to approve/merge once that is done!

**Comment by stumblefiend** [comment]
Hi @jerelmiller, I update to address the linter issue.  Please have another look.

**Review by jerelmiller — APPROVED** [review]
Thanks so much for updating this! Last thing before I merge. Would you mind signing the CLA? You will only need to do this once!

**Comment by stumblefiend** [comment]
@jerelmiller I'm not sure what is up with the CLA.  I've clicked the link twice to view the CLA.  It shows me it is signed and I saw the confirmation screen yesterday when I signed it.  I clicked the recheck button above, but it doesn't do anything.  Any ideas what could be the issue?

**Comment by jerelmiller** [comment]
Oh how weird. I'll ask our open source team about this. Since you've gone ahead and tried, I'll go ahead and merge while I try and figure out why the CLA isn't working.

**Comment by stumblefiend** [comment]
Actually, when I visit the CLA link again right now, it is asking me to sign it again.  I did so and receive the same screen I saw yesterday (see attached screenshot).  However, clicking "recheck" above still doesn't do anything.

Screen Shot 2021-02-25 at 9 33 03 AM

**Comment by stumblefiend** [comment]
Thanks for your responsiveness @jerelmiller and for the merge!  New Relic provided a great doc experience!

**Comment by jerelmiller** [comment]
You're very welcome! That is really great feedback to hear!

**Pull request merged**
