### PR TITLE
Set site back to default index page

### PR DESCRIPTION
**Pull request by jpvajda**
## Description

Reverted back the home page with mark's video.

### CODE REVIEW

**Comment by jpvajda** [comment]
Don't merge yet, as the CSS isn't right.  I can't seem to figure out the CSS for the video to show on max width screen size. It shows for other screen sizes though..

**Comment by jpvajda** [comment]
@jerelmiller  @caylahamann  Any thoughts on my dilemma?

**Comment by jpvajda** [comment]
Jemiah updated the home page for APAC dates in another PR and I merged it in #858  so we can hold this PR in reserve and merge it in after APAC nerddays is over on 10/22 @jerelmiller

**Comment by jerelmiller** [comment]
Closing in favor of #961

**Pull request closed without merging**
