### PR TITLE
Relicans update

### PR DESCRIPTION
**Pull request by jpvajda**
Resolves yarn lock issues for https://github.com/newrelic/developer-website/pull/1573 and merged in the relican page changes.

### CODE REVIEW

**Comment by jpvajda** [comment]
helping @laurenelee to get this PR to pass checks, I'm curious as why there is still a yarn lock file conflict...

**Comment by jpvajda** [comment]
GOT IT.. 🥳 🎈

**Comment by LizBaker** [comment]
I noticed Ali's last name was updated in the relican's page but not the nerdlog page, assuming it should change in both but just want to double check

**Comment by jpvajda** [comment]
@LizBaker good catch I change the name in `nerdlogData.js` which is where the name was sourced from on that page.

**Review by nr-kkenney — APPROVED** [review]
lgtm

**Pull request merged**
